name: CD

on:
  push:
    branches:
      - PROD

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.Flare_Key }}" > ~/.ssh/flare-key.pem
          chmod 600 ~/.ssh/flare-key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/flare-key.pem ubuntu@${{ secrets.Flare_IP }} << 'EOF'
          cd /home/ubuntu/flare
          git pull origin PROD
          EOF

