name: CD

on:
  push:
    branches:
      - PROD

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/${FLARE_KEY}.pem ubuntu@${FLARE_IP} << 'EOF'
            cd /home/ubuntu/flare
            git pull origin PROD
          EOF
